### ISSUE TITLE
[Admin] Adding authentication for admin

### ISSUE THREAD

**Issue by louis-forite** [zalando-incubator/pazuzu-ui#9]
Administrator must log into the application in order to be able to administration tasks. Therefore an authentication space should be created in the app

**Comment by truemped** [comment]
Hi @Volland. As you moved the ticket to in-progress is there any code lying around? I cannot find a branch/fork/pr so I'm hoping there is some code on your machine?! :-)

**Comment by pgronkiewicz** [comment]
Visible for non-logged in user:
- All approved features with details

Visible for admins:
- Authentication panel, where admin can manage other admins
- List of unapproved features with approval option (for now just 1 approval needed)

Open to discussion:
- Adding features has 2 options:
 1. User role, where you have to log in and everyone is allowed to log in
 2. Allow anonymous upload, with some captcha

**Comment by truemped** [comment]
So, the underlying for like authentication with OAuth etc. was done in #60. The detailed UI on roles/admins/approvals is still to be done.
